version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - echo "Packaging Lambda function..."
      - zip -r lambda_function.zip .
artifacts:
  files:
    - lambda_function.zip
