version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo "Zipping Lambda function..."
      - zip lambda.zip lambda_function.py
      - echo "Packaging CloudFormation template..."
      - aws cloudformation package \
          --template-file lambda-cicd.yaml \
          --s3-bucket $S3_BUCKET \
          --output-template-file output-template.yaml

artifacts:
  files:
    - output-template.yaml
    - lambda.zip
